""" add last_delay_alert_sent_at to medication_protocols and DOSE_ATRASADA to NotificationType

Revision ID: 626fbed52063
Revises: c8d0a206b46d
Create Date: 2026-07-08 19:02:00.147723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '626fbed52063'
down_revision: Union[str, Sequence[str], None] = 'c8d0a206b46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_protocols', sa.Column('last_delay_alert_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'DOSE_ATRASADA'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication_protocols', 'last_delay_alert_sent_at')
    # ### end Alembic commands ###
