"""add_weekly_report

Revision ID: 8d10330fcd58
Revises: 8adcccf53299
Create Date: 2026-08-23 20:19:58.311435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d10330fcd58'
down_revision: Union[str, Sequence[str], None] = '8adcccf53299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'REPORT_ADDED'")
    op.create_table('weekly_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('care_recipient_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mood', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('diet', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('wellbeing_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['care_group_members.id'], ),
    sa.ForeignKeyConstraint(['care_recipient_id'], ['care_recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reports_care_recipient_id'), 'weekly_reports', ['care_recipient_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_report_date'), 'weekly_reports', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_reports_report_date'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_care_recipient_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    # ### end Alembic commands ###
