"""add_scheduling_to_medication

Revision ID: c8d0a206b46d
Revises: b32574b37a0f
Create Date: 2026-07-08 17:31:06.343187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c8d0a206b46d'
down_revision: Union[str, Sequence[str], None] = 'b32574b37a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication_protocols', sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('medication_protocols', sa.Column('assignee_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_medication_protocols_next_due_at'), 'medication_protocols', ['next_due_at'], unique=False)
    op.create_foreign_key(None, 'medication_protocols', 'care_group_members', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medication_protocols', type_='foreignkey')
    op.drop_index(op.f('ix_medication_protocols_next_due_at'), table_name='medication_protocols')
    op.drop_column('medication_protocols', 'assignee_id')
    op.drop_column('medication_protocols', 'next_due_at')
    # ### end Alembic commands ###
